# Generated by Django 2.2.7 on 2019-11-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_auto_20191122_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmer',
            name='name',
            field=models.CharField(default='Null', max_length=200),
        ),
    ]
